// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profession.proto

package position_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profession struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profession) Reset()         { *m = Profession{} }
func (m *Profession) String() string { return proto.CompactTextString(m) }
func (*Profession) ProtoMessage()    {}
func (*Profession) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8218efded744475, []int{0}
}

func (m *Profession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profession.Unmarshal(m, b)
}
func (m *Profession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profession.Marshal(b, m, deterministic)
}
func (m *Profession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profession.Merge(m, src)
}
func (m *Profession) XXX_Size() int {
	return xxx_messageInfo_Profession.Size(m)
}
func (m *Profession) XXX_DiscardUnknown() {
	xxx_messageInfo_Profession.DiscardUnknown(m)
}

var xxx_messageInfo_Profession proto.InternalMessageInfo

func (m *Profession) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profession) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateProfession struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfession) Reset()         { *m = CreateProfession{} }
func (m *CreateProfession) String() string { return proto.CompactTextString(m) }
func (*CreateProfession) ProtoMessage()    {}
func (*CreateProfession) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8218efded744475, []int{1}
}

func (m *CreateProfession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfession.Unmarshal(m, b)
}
func (m *CreateProfession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfession.Marshal(b, m, deterministic)
}
func (m *CreateProfession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfession.Merge(m, src)
}
func (m *CreateProfession) XXX_Size() int {
	return xxx_messageInfo_CreateProfession.Size(m)
}
func (m *CreateProfession) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfession.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfession proto.InternalMessageInfo

func (m *CreateProfession) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProfessionId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfessionId) Reset()         { *m = ProfessionId{} }
func (m *ProfessionId) String() string { return proto.CompactTextString(m) }
func (*ProfessionId) ProtoMessage()    {}
func (*ProfessionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8218efded744475, []int{2}
}

func (m *ProfessionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfessionId.Unmarshal(m, b)
}
func (m *ProfessionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfessionId.Marshal(b, m, deterministic)
}
func (m *ProfessionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfessionId.Merge(m, src)
}
func (m *ProfessionId) XXX_Size() int {
	return xxx_messageInfo_ProfessionId.Size(m)
}
func (m *ProfessionId) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfessionId.DiscardUnknown(m)
}

var xxx_messageInfo_ProfessionId proto.InternalMessageInfo

func (m *ProfessionId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAllProfessionRequest struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProfessionRequest) Reset()         { *m = GetAllProfessionRequest{} }
func (m *GetAllProfessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProfessionRequest) ProtoMessage()    {}
func (*GetAllProfessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8218efded744475, []int{3}
}

func (m *GetAllProfessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProfessionRequest.Unmarshal(m, b)
}
func (m *GetAllProfessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProfessionRequest.Marshal(b, m, deterministic)
}
func (m *GetAllProfessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProfessionRequest.Merge(m, src)
}
func (m *GetAllProfessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProfessionRequest.Size(m)
}
func (m *GetAllProfessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProfessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProfessionRequest proto.InternalMessageInfo

func (m *GetAllProfessionRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAllProfessionRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetAllProfessionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAllProfessionResponse struct {
	Professions          []*Profession `protobuf:"bytes,1,rep,name=professions,proto3" json:"professions,omitempty"`
	Count                uint32        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAllProfessionResponse) Reset()         { *m = GetAllProfessionResponse{} }
func (m *GetAllProfessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllProfessionResponse) ProtoMessage()    {}
func (*GetAllProfessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8218efded744475, []int{4}
}

func (m *GetAllProfessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProfessionResponse.Unmarshal(m, b)
}
func (m *GetAllProfessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProfessionResponse.Marshal(b, m, deterministic)
}
func (m *GetAllProfessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProfessionResponse.Merge(m, src)
}
func (m *GetAllProfessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllProfessionResponse.Size(m)
}
func (m *GetAllProfessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProfessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProfessionResponse proto.InternalMessageInfo

func (m *GetAllProfessionResponse) GetProfessions() []*Profession {
	if m != nil {
		return m.Professions
	}
	return nil
}

func (m *GetAllProfessionResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRes) Reset()         { *m = DeleteRes{} }
func (m *DeleteRes) String() string { return proto.CompactTextString(m) }
func (*DeleteRes) ProtoMessage()    {}
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8218efded744475, []int{5}
}

func (m *DeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRes.Unmarshal(m, b)
}
func (m *DeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRes.Marshal(b, m, deterministic)
}
func (m *DeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRes.Merge(m, src)
}
func (m *DeleteRes) XXX_Size() int {
	return xxx_messageInfo_DeleteRes.Size(m)
}
func (m *DeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Profession)(nil), "genproto.Profession")
	proto.RegisterType((*CreateProfession)(nil), "genproto.CreateProfession")
	proto.RegisterType((*ProfessionId)(nil), "genproto.ProfessionId")
	proto.RegisterType((*GetAllProfessionRequest)(nil), "genproto.GetAllProfessionRequest")
	proto.RegisterType((*GetAllProfessionResponse)(nil), "genproto.GetAllProfessionResponse")
	proto.RegisterType((*DeleteRes)(nil), "genproto.DeleteRes")
}

func init() { proto.RegisterFile("profession.proto", fileDescriptor_a8218efded744475) }

var fileDescriptor_a8218efded744475 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xaa, 0xc5, 0x4e, 0xac, 0x94, 0xa5, 0x68, 0x44, 0x90, 0x92, 0x83, 0xf4, 0x14,
	0x45, 0xc1, 0xbb, 0x7f, 0x40, 0xbc, 0xc9, 0x1e, 0xf5, 0x20, 0xb5, 0x79, 0xd1, 0x85, 0x74, 0x27,
	0x66, 0xb6, 0x7e, 0x7e, 0x71, 0xeb, 0x36, 0x8b, 0xde, 0xe6, 0xcd, 0xfc, 0xe6, 0xbd, 0x61, 0x68,
	0xd2, 0x76, 0x5c, 0x43, 0xc4, 0xb0, 0x2d, 0xdb, 0x8e, 0x1d, 0xab, 0xbd, 0x77, 0x58, 0x5f, 0x15,
	0x17, 0x44, 0x4f, 0xdb, 0xa9, 0x3a, 0xa0, 0xd4, 0x54, 0x79, 0x32, 0x4b, 0xe6, 0x23, 0x9d, 0x9a,
	0x4a, 0x29, 0xda, 0xb1, 0x8b, 0x15, 0xf2, 0xd4, 0x77, 0x7c, 0x5d, 0x9c, 0xd1, 0xe4, 0xae, 0xc3,
	0xc2, 0x21, 0xda, 0x0b, 0x5c, 0x12, 0x71, 0xa7, 0xb4, 0xdf, 0x13, 0x8f, 0xd5, 0x5f, 0xef, 0xe2,
	0x85, 0x8e, 0x1e, 0xe0, 0x6e, 0x9a, 0xa6, 0xa7, 0x34, 0x3e, 0xd7, 0x10, 0xa7, 0xa6, 0xb4, 0xdb,
	0x98, 0x95, 0x71, 0x9e, 0x1e, 0xeb, 0x8d, 0x50, 0x87, 0x34, 0xe4, 0xba, 0x16, 0x38, 0x7f, 0xce,
	0x58, 0xff, 0xaa, 0x6d, 0xf8, 0x20, 0x0a, 0xff, 0xa0, 0xfc, 0xbf, 0xb9, 0xb4, 0x6c, 0x05, 0xea,
	0x9a, 0xb2, 0xfe, 0x21, 0x92, 0x27, 0xb3, 0xc1, 0x3c, 0xbb, 0x9c, 0x96, 0xe1, 0x25, 0x65, 0xb4,
	0x12, 0x83, 0x3f, 0x57, 0x2d, 0x79, 0x6d, 0x43, 0xfc, 0x46, 0x14, 0x19, 0x8d, 0xee, 0xd1, 0xc0,
	0x41, 0x43, 0x6e, 0x4f, 0x9e, 0x8f, 0x83, 0xcd, 0x79, 0xcb, 0x62, 0x9c, 0x61, 0xfb, 0x2a, 0xe8,
	0xbe, 0xcc, 0x12, 0x6f, 0x43, 0xdf, 0xbf, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xb5, 0x8f,
	0xfd, 0x8f, 0x01, 0x00, 0x00,
}
